### PR TITLE
longer branch names get a false postive - no task number reported

### PR DESCRIPTION
**Pull request by nvreynolds**
I'm not sure why this was using 

        and

### CODE REVIEW

**Comment by Blue-Dog-Archolite** [comment]
LGTM

**Comment by robertzk** [comment]
Thanks!

**Comment by robertzk** [comment]
@Blue-Dog-Archolite how've you been?

**Comment by Blue-Dog-Archolite** [comment]
@robertzk Good. Working too much but hey. That is life.

**Comment by Ferdy89** [comment]
@nvreynolds @robertzk Is this really the behavior desired? With this, the title, the body and the commits of the PR must contain the word "pivotal" and an 8 digit number. I think the `and` was probably the behavior desired

**Comment by robertzk** [comment]
Can you submit a PR?

On Thu, May 28, 2015 at 1:02 PM, Fernando Seror Garcia <
notifications@github.com> wrote:

> @nvreynolds <https://github.com/nvreynolds> @robertzk
> <https://github.com/robertzk> Is this really the behavior desired? With
> this, the title, the body and the commits of the PR must contain the word
> "pivotal" and an 8 digit number. I think the and was probably the
> behavior desired
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robertzk/meyerbot/pull/3#issuecomment-106534997>.
>



-- 
-Robert Krzyzanowski

**Comment by Ferdy89** [comment]
@robertzk https://github.com/robertzk/meyerbot/pull/4

**Pull request merged**
