### PR TITLE
accounting for rspec

### PR DESCRIPTION
**Pull request by nvreynolds**
@robertzk we are starting to use rspec

https://github.com/avantcredit/avant-basic/pull/4823

### CODE REVIEW

**Comment by MissingHandle** [comment]
:+1:

**Comment by Blue-Dog-Archolite** [comment]
Going to merge this sucker? Or are you letting Meyer fall behind?

**Comment by Blue-Dog-Archolite** [comment]
Going to merge this sucker? Or are you letting Meyer fall behind?

**Comment by nvreynolds** [comment]
the legend shows his face!

**Comment by nvreynolds** [comment]
hope things are going well for you @Blue-Dog-Archolite

**Pull request merged**
